# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: pr
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - run: npm test
    format:
        name: check code format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - run: npm run check-format
